<<<<<<< HEAD
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
=======
theme: jekyll-theme-slate
>>>>>>> 95da70d9dc9b301fc4856d57ab9d8a2d0b7673c2

# Site settings
title: GVENCK
email: gvenck.esalq@gmail.com
description: > # this means to ignore newlines until "baseurl:"
<<<<<<< HEAD
  Copyright© 2018. All rights reserved.
baseurl: "" # the subpath of your site, e.g. /blog
=======
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
>>>>>>> 95da70d9dc9b301fc4856d57ab9d8a2d0b7673c2
url: "http://gvenck.github.io" # the base hostname & protocol for your site
twitter_username: gvenck
github_username:  gvenck

# Build settings
markdown: kramdown
<<<<<<< HEAD
theme: jekyll-theme-slate
=======
permalink: /:year/:title:output_ext
>>>>>>> 95da70d9dc9b301fc4856d57ab9d8a2d0b7673c2
